#!/bin/bash

# GUÍA RÁPIDA - Inicia aquí

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   SERVICIO OAUTH2 CON CONSUMO DE API REST - GUÍA RÁPIDA   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 ¿QUÉ HACE ESTE SERVICIO?"
echo "   • Autentica usuarios con OAuth2 y JWT"
echo "   • Ofrece endpoint protegido /api/data/hola"
echo "   • Devuelve 'Hola Mundo' en JSON"
echo "   • Solo accesible si estás autenticado"
echo ""
echo "🚀 PARA EJECUTAR:"
echo "   1. Abre terminal en: /workspaces/actividad_2/demoOAUTH2-master"
echo "   2. Ejecuta: mvn spring-boot:run"
echo "   3. El servicio estará en: http://localhost:8080"
echo ""
echo "🔐 CREDENCIALES DE PRUEBA:"
echo "   Usuario: user"
echo "   Contraseña: password"
echo ""
echo "💡 PARA PROBAR EN OTRO TERMINAL:"
echo ""
echo "   1️⃣  LOGIN (obtener token):"
echo "   curl -X POST http://localhost:8080/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"user\",\"password\":\"password\"}'"
echo ""
echo "   Copia el 'token' de la respuesta"
echo ""
echo "   2️⃣  USAR ENDPOINT PROTEGIDO:"
echo "   curl -X GET http://localhost:8080/api/data/hola \\"
echo "     -H 'Authorization: Bearer {TOKEN_AQUI}'"
echo ""
echo "   ✅ VERÁS: 'Hola Mundo' en JSON (solo si estás autenticado)"
echo "   ❌ SIN TOKEN: Error 401 Unauthorized"
echo ""
echo "📖 DOCUMENTACIÓN:"
echo "   • README.md         - Descripción completa"
echo "   • EJEMPLOS.md       - Ejemplos con curl y Postman"
echo "   • ESTRUCTURA.md     - Estructura del proyecto"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
