spring.application.name=demoAuth

# Puerto del servidor
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.demoAuth=DEBUG

# OAuth2 Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
